# Generated by Django 4.0.4 on 2022-05-15 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlboMacs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='img',
        ),
        migrations.AddField(
            model_name='achievement',
            name='image',
            field=models.ImageField(default='img/300-erasmus-luiss_4.jpeg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='img/300-erasmus-luiss_4.jpeg', upload_to=''),
        ),
    ]
