# Generated by Django 4.0.4 on 2022-05-15 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlboMacs', '0002_remove_achievement_img_achievement_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='img',
        ),
    ]
