# Generated by Django 4.0.4 on 2022-05-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlboMacs', '0006_course_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
        migrations.AlterField(
            model_name='person',
            name='year_in_school',
            field=models.CharField(choices=[('FR', 'Freshman'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate'), ('PR', 'Professor')], default='FR', max_length=2),
        ),
    ]
