# Generated by Django 4.0.4 on 2022-05-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlboMacs', '0007_rename_news_new_alter_person_year_in_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
