# Generated by Django 4.0.4 on 2022-05-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlboMacs', '0008_alter_course_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_year',
            field=models.CharField(choices=[(1, 'First year'), (2, 'Second year'), (3, 'Third year')], default=1, max_length=1),
        ),
    ]
