# Generated by Django 4.0.4 on 2022-05-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlboMacs', '0010_alter_course_course_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_year',
            field=models.IntegerField(choices=[(1, 'First year'), (2, 'Second year'), (3, 'Third year')], default=1),
        ),
    ]
