# Generated by Django 4.0.4 on 2022-05-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlboMacs', '0011_alter_course_course_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_semester',
            field=models.IntegerField(choices=[(1, 'First semester'), (2, 'Second semester')], default=1),
        ),
    ]
