# Generated by Django 4.0.4 on 2022-05-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlboMacs', '0014_remove_course_teacher_course_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='achievement',
            name='person',
        ),
        migrations.AddField(
            model_name='achievement',
            name='person',
            field=models.ManyToManyField(to='AlboMacs.person'),
        ),
    ]
