# Generated by Django 4.0.4 on 2022-05-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlboMacs', '0015_remove_achievement_person_achievement_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='address',
            field=models.CharField(blank=True, default='@luiss.it', max_length=50, null=True),
        ),
    ]
