# Generated by Django 4.0.4 on 2022-05-24 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlboMacs', '0017_alter_achievement_description_alter_new_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(default='img/300-erasmus-luiss_4.jpeg', upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('accomplish_date', models.DateField(blank=True, null=True)),
                ('person', models.ManyToManyField(to='AlboMacs.person')),
            ],
        ),
    ]
