# Generated by Django 4.0.4 on 2022-05-24 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlboMacs', '0018_achievement2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Achievement2',
        ),
    ]
